# Generated by Django 5.1.7 on 2025-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50, unique=True)),
                ('slug_field', models.SlugField(unique=True)),
                ('Category_description', models.TextField(blank=True, max_length=250)),
                ('Category_image', models.ImageField(blank=True, upload_to='images/category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
